### ISSUE TITLE
The plugin is not working: somehow `end` is not being inserted

### ISSUE THREAD

**Issue by wookayin** [RRethy/nvim-treesitter-endwise#11]
I am having a hard time making this plugin working. `:TSModuleInfo` shows endwise is loaded and active for the current filetype (lua, ruby, etc.), but it is not inserting `end` automatically for me. What am I doing wrong or how can I troubleshoot?

I am on neovim 0.7.0 nightly, NVIM v0.7.0-dev+953-gd0493d110 (tried on 0.6.2 but it's the same).

In my treesitter config, I have endwise enabled:
```lua
require'nvim-treesitter.configs'.setup {
 -- one of "all", "maintained" (parsers with maintainers), or a list of languages
  ensure_installed = "maintained",

  -- List of parsers to ignore installing
  ignore_install = { },

  highlight = {
    enable = false,
  },
  playground = {
     ...
  },

  -- nvim-treesitter-endwise
  endwise = {
    enable = true,
  },
}
```

I have ruby, lua, vimscript parser for treesitter installed, and confirm that TS is working fine from `:TSPlaygroundToggle`.

Given the plugin/module activated, however, I never see this working: on a new ruby file, I type `module Foo` and then hit `<CR>`. I expect `end` would be inserted, but nothing happened.
```
module Foo
    |
```

Any hints or insight on how I could troubleshoot/debug the plugin?

**Comment by wookayin** [comment]
@RRethy Why did you close this issue?

**Comment by RRethy** [comment]
Mate, you gotta learn to talk with respect, otherwise don't use this plugin. Fork it or make your own.

Reference: https://github.com/RRethy/nvim-treesitter-endwise/issues/10#issuecomment-1030972919
