### ISSUE TITLE
Feature Request: do/end match jumping with %

### ISSUE THREAD

**Issue by knpwrs** [RRethy/nvim-treesitter-endwise#12]
**Is your feature request related to a problem? Please describe.**

I would like to jump to matching `do`/`end` pairs with `%` in neovim.

**Describe the solution you'd like**

There is prior art for this concept: https://www.vim.org/scripts/script.php?script_id=290, I think powering this functionality on treesitter would be killer.

**Comment by khaveesh** [comment]
https://github.com/andymass/vim-matchup

**Comment by RRethy** [comment]
Out of scope for this plugin, as the above comment mentions tho vim-matchup does this and support tree-sitter.

**Comment by knpwrs** [comment]
Awesome, thank you!

@RRethy, would you be open to a PR to add a "similar plugins" or "companion plugins" section to the README? I think it would be great to link to https://github.com/andymass/vim-matchup there.

**Comment by RRethy** [comment]
Tbh the only plugin I would mention in the is `vim-endwise` which is already mentioned, I think vim-matchup is sufficiently different that it would be clutter.

**Comment by RRethy** [comment]
Didn't mean to reopen this.
