### ISSUE TITLE
Segfault on HEAD with endwise enabled.

### ISSUE THREAD

**Issue by dsully** [RRethy/nvim-treesitter-endwise#15]
nvim-treesitter-endwise is causing a segfault using Neovim @ HEAD. See: https://github.com/neovim/neovim/issues/18079 for the details.

**Comment by zeertzjq** [comment]
Can `nvim_get_mode()` be used in this plugin instead of FFI?

**Comment by RRethy** [comment]
API functions cannot be used, see https://github.com/RRethy/nvim-treesitter-endwise/blob/f653101e056cebcee71b47b8adb93d3a878cda36/lua/nvim-treesitter/endwise.lua#L195-L202 The FFI call was to fix https://github.com/RRethy/nvim-treesitter-endwise/issues/9.

I see that the signature of `get_mode` has changed which is unfortunate. I'll have to think about how to go about fixing this.

Edit: It seems like `vim.api.nvim_get_mode()` doesn't error as I thought it would based on https://github.com/neovim/neovim/issues/17273 but it seems I misunderstood.
