### ISSUE TITLE
How to install?

### ISSUE THREAD

**Issue by faqndo97** [RRethy/nvim-treesitter-endwise#16]
Hi! Sorry for the dumb question but I've been trying to install this and I'm not sure how.

I'm using Neovim, and I'm testing LunarVim right now.

Should I install this plugin? Like `Plug "RRethy/nvim-treesitter-endwise"` or similar?

I'm asking because I configured it as documented but seems that It's not working.

**Comment by RRethy** [comment]
Yes, you'll need to install the plugin following whatever the installation process is for your specific plugin manager, as well as doing the required configuration steps in the README.

**Comment by faqndo97** [comment]
Cool, after that and restart nvim everything works perfectly! Thanks, great work!

**Comment by floydj** [comment]
I'm having trouble installing too, and I think that I'm missing something that may be implied here on the readme, but I can't figure it out.

Have the following:

```lua
  use {
    'nvim-treesitter/nvim-treesitter',
    run = ':TSUpdate'
  }

  use "RRethy/nvim-treesitter-endwise"

```

and

```lua
require('nvim-treesitter').setup()
require('nvim-treesitter.configs').setup {
    
    endwise = {
        enable = true,
    },
}
```

I've done `:TSInstall ruby` as indicated on the TS site, and of course ran `:PackerInstall`.

But when I type `def`<TAB> or `def<Enter>` I can't get the `end` to automatically appear in a ruby file.

Would appreciate any help with getting this going if you have some time - I'm sure I'm missing something simple.  Thanks

**Comment by RRethy** [comment]
Try `def foo<Enter>`, `def end` isn't really valid Ruby so `end` won't be added for `dev<Enter>`.

Also, `<Enter>` == `<CR>` in Vim lingo.

**Comment by floydj** [comment]
That did it.  Thank you!
