### ISSUE TITLE
Support ruby `class << self`

### ISSUE THREAD

**Issue by catlee** [RRethy/nvim-treesitter-endwise#18]
When I type `class << self` in ruby, I would like endwise to add the closing `end` statement like it does for regular class definitions.

**Comment by RRethy** [comment]
Not sure what happened here, I remember adding `singleton_class` queries a while back for this but I don't see them anywhere in the git history 😕

**Comment by catlee** [comment]
awesome, thanks!

I wasn't sure if this was going to be possible since the treesitter playground was just showing me a single `self` node for `class << self`
