### ISSUE TITLE
Lua function elseif also will insert end

### ISSUE THREAD

**Issue by Ritzier** [RRethy/nvim-treesitter-endwise#19]
Before:
```
if true then
    print('true')
elseif true then |
else
   print('false')
end
```
Input <CR>:
```
if true then
    print('true')
elseif true then
    |
end
else
   print('false')
end
```

**Comment by RRethy** [comment]
Unable to replicate this behaviour and the [Lua queries](https://github.com/RRethy/nvim-treesitter-endwise/blob/master/queries/lua/endwise.scm) don't have any mention of `elseif`. I will add a test for this, but it's something going on in your config.

**Comment by Ritzier** [comment]
I found that problem!
Removed this line nvim-autopairs add rules and Endwise work good!!!:
``` 
require('nvim-autopairs').add_rules(require "nvim-autopairs.rules.endwise-lua")
```
