### ISSUE TITLE
Error on load:  nvim-treesitter.ts_utils.is_in_node_range is deprecated: use vim.treesitter.is_in_node_range

### ISSUE THREAD

**Issue by 2KAbhishek** [RRethy/nvim-treesitter-endwise#22]
Seeing this deprecation message on load, also not getting it to function as shown in the demo

```lua
nvim-treesitter.ts_utils.is_in_node_range is deprecated: use vim.treesitter.is_in_node_range
```

I'm using Lazy.nvim and have added the configs:

```lua
    endwise = {
        enable = true,
    },
```

**Expected behavior**
endwise loads without errors and works

**Screengrab**
![Screenshot 2023-02-26 at 2 45 09 AM](https://user-images.githubusercontent.com/25423853/221379912-712bcfb3-d3c0-4aec-bf24-1525ab430484.png)

**Additional context**

**Comment by 2KAbhishek** [comment]
Will open a new one with after more debugging

**Comment by LandonSchropp** [comment]
@2KAbhishek Any luck with this? I'm using LazyVim and while I don't see this notification, this plugin still doesn't work for me.

**Comment by RRethy** [comment]
@LandonSchropp make a minimal init.lua

**Comment by 2KAbhishek** [comment]
@LandonSchropp I was able to make it work after removing tpope/endwise from my list

Though it doesn't work for me in lua, only ruby

**Comment by LandonSchropp** [comment]
@2KAbhishek Unfortunately I don't have `tpope/endwise` in my list. 😞

**Comment by LandonSchropp** [comment]
@RRethy Good call. I tried to repro, but when I created a minimal config I didn't see any problems anymore. After switching back to my regular config, everything seems to be working now, even though the config hasn't changed. Maybe something updated, or Lazy.nvim was out of sync. ¯\\\_(ツ)\_/¯

I'll open an issue if I run into a reproducable problem. Thanks!
