### ISSUE TITLE
Question: How to run test on this repository?

### ISSUE THREAD

**Issue by mamantoha** [RRethy/nvim-treesitter-endwise#28]
Hi there. It's not a bug. I have a question and need guidance on how to run tests in this repository. 

I tried running `ruby tests/runner.rb`, but encountered an error related to a missing module `nvim-treesitter`. The error message indicates that the module cannot be found.

```
...
nvim-treesitter-endwise/tests/init.lua:5: module 'nvim-treesitter.configs' not found
...
```

Could someone please provide instructions if possible? Thank you!

I tried running the command on both Linux (Manjaro) and macOS.

**Comment by RRethy** [comment]
`ruby test/runner.rb` is sufficient. You'll need `nvim-treesitter` installed in the same directory as nvim-treesitter-endwise which is why you see the error. You can do a `ls ..` in the nvim-treesitter-endwise repo to see if it's installed in the right place.
