### ISSUE TITLE
Update README to show that tpope/vim-endwise must be installed

### ISSUE THREAD

**Issue by gsinclair** [RRethy/nvim-treesitter-endwise#29]
This is not a software bug, but a request to improve the documentation.

I thought this plugin was a _replacement_ for `tpope/vim-endwise`, and was wondering why (when I followed the quick-start instructions) I was not getting any functionality.

**Comment by RRethy** [comment]
tpope/vim-endwise does not have to be installed, this plugin is a replacement for tpope/vim-endwise. In fact, it's a bad idea to install it alongside this plugin. Your config likely was bad.
