### ISSUE TITLE
Create comma after function in map [Lua]

### ISSUE THREAD

**Issue by podratz** [RRethy/nvim-treesitter-endwise#33]
**Describe the bug**
When inside a map in Lua and adding another key, no comma is inserted after the def ... end

**Expected behavior**
I'd expect a comma to be inserted as otherwise I need to manually go to behind the function I created and insert it which is cumbersome.

**Comment by RRethy** [comment]
Not possible and not planned with the architecture of this plugin.

**Comment by podratz** [comment]
Ok thanks
