### ISSUE TITLE
Handling cases when cursor is not at the end of line

### ISSUE THREAD

**Issue by simonmandlik** [RRethy/nvim-treesitter-endwise#36]
**Is your feature request related to a problem? Please describe.**
When working on https://github.com/RRethy/nvim-treesitter-endwise/pull/35, I struggled a lot when dealing with cases when the cursor is not at the very end of the line.

Pseudocode examples:

```
function f(<cursor>)
```

leads to

```
function f(
    <cursor>
end)
```

or for example

```
if f(<cursor>)
```

leads to

```
if f(
    <cursor>
)
```

I guess this behavior applies to multiple languages, not only julia. For example, try the following test for lua:

```rb
test "lua, function", <<~END
-function foo(█)
+function foo(
+  )
END
```

Maybe I'm missing something, but writing this in TS queries seems quite difficult — I have to always capture the last `")"`, which leads to many corner cases and queries become large.

**Describe the solution you'd like**

I have only written some queries and I don't know anything about internals of this plugin. What is the preferred way to deal with that?

What if the following heuristic was used: Whenever on the current line there still is a non-whitespace character **after** the cursor, do not add an `"end"`? Is there any case where this would be undesirable?

Thanks!

**Comment by RRethy** [comment]
> What if the following heuristic was used: Whenever on the current line there still is a non-whitespace character after the cursor, do not add an "end"? Is there any case where this would be undesirable?

Yes it would be undesirable. I don't want to not add an `end` when it's needed. We have the heuristic that if the text that follows the cursor is alphanumeric, then put it on the line of the cursor, if it's non-alphanumeric then put it on the line of the `end`. It's especially useful to handling functions defined as arguments.

The code for this is at https://github.com/RRethy/nvim-treesitter-endwise/blob/master/lua/nvim-treesitter/endwise.lua#L81.

This test shows what happens, https://github.com/RRethy/nvim-treesitter-endwise/blob/master/tests/endwise/lua.rb#L185-L189.

**Comment by RRethy** [comment]
For what it's worth, there is no perfect solution for this since we don't get a full syntax tree, we have to interpret a broken syntax tree, these are tradeoffs I made a long time ago and honestly aren't going to change.

**Comment by simonmandlik** [comment]
> We have the heuristic that if the text that follows the cursor is alphanumeric, then put it on the line of the cursor, if it's non-alphanumeric then put it on the line of the end. It's especially useful to handling functions defined as arguments.

Yes, I have noticed. It works great in cases like 

```
function f(a, <cursor>b)
```

but not when it is in front of "`,`" or "`)`". 

Sow how about adding these some punctuation mark characters to the regexp here https://github.com/RRethy/nvim-treesitter-endwise/blob/master/lua/nvim-treesitter/endwise.lua#L81?
