### ISSUE TITLE
Fails on <C-C>

### ISSUE THREAD

**Issue by dewyze** [RRethy/nvim-treesitter-endwise#7]
For better or worse, I use `<C-C>` instead of escape most of the time. Using that produced this error:

```
Error executing  vim.on_key Lua callback: vim.lua:498: Error executing 'on_key' with ns_ids '2'
    Messages: Keyboard interrupt
stack traceback:
        [C]: in function 'error'
        vim.lua:498: in function <vim.lua:485>
```

Let me know if I can do anything to help debug!

**Comment by RRethy** [comment]
Opened an issue in neovim/neovim, https://github.com/neovim/neovim/issues/17273. In the meantime, I'll wrap calls to `vim.fn.*` functions with `schedule_wrap` since this looks like an issue with the event loop.

**Comment by RRethy** [comment]
The fix from earlier will be permanent, it needs to be schedule wrapped. https://github.com/neovim/neovim/issues/17273#issuecomment-1028361719
