### ISSUE TITLE
`end` block inserted twice when using `Raimondi/delimitMate`

### ISSUE THREAD

**Issue by noib3** [RRethy/nvim-treesitter-endwise#9]
I have `<CR>` mapped to `<Plug>delimitMateCR` in insert mode, which somehow causes the `end` block to be inserted twice (tested w/ Lua files).

[Here's a video](https://asciinema.org/a/iF2KWHN6w5BB1onyDoWIMA4nK). Can you reproduce the behaviour?

**Comment by RRethy** [comment]
Fixed by https://github.com/RRethy/nvim-treesitter-endwise/commit/4a12ecf91a1184d4595c7f63c3adb87fae079732
